"""Generate src/radios/country_names.py from the Unicode CLDR.

The country names come from the English locale of the Unicode Common Locale
Data Repository (CLDR), the data browsers and operating systems use too. The
codes are the ISO 3166-1 alpha-2 codes pycountry knows, plus Kosovo, which has
a user-assigned code the Radio Browser API uses.

Run it with `poetry run python scripts/update_country_names.py`.
"""

import json
import pathlib
import urllib.request

import pycountry

CLDR_VERSION = "48.2.3"
CLDR_URL = (
    "https://raw.githubusercontent.com/unicode-org/cldr-json/"
    f"{CLDR_VERSION}/cldr-json/cldr-localenames-full/main/en/territories.json"
)
OUTPUT = pathlib.Path(__file__).parent.parent / "src" / "radios" / "country_names.py"

# Where the CLDR default name reads awkwardly in a list of stations, the short
# or variant name CLDR also has is used instead.
ALTERNATIVES = {
    "CD": "CD-alt-variant",  # Congo (DRC), instead of Congo - Kinshasa
    "CG": "CG-alt-variant",  # Congo (Republic), instead of Congo - Brazzaville
    "HK": "HK-alt-short",  # Hong Kong, instead of Hong Kong SAR China
    "MM": "MM-alt-short",  # Myanmar, instead of Myanmar (Burma)
    "MO": "MO-alt-short",  # Macao, instead of Macao SAR China
    "PS": "PS-alt-short",  # Palestine, instead of Palestinian Territories
}


def main() -> None:
    """Fetch the country names, and write them out as a Python module."""
    with urllib.request.urlopen(CLDR_URL, timeout=30) as response:  # noqa: S310
        territories = json.load(response)["main"]["en"]["localeDisplayNames"][
            "territories"
        ]

    codes = sorted({country.alpha_2 for country in pycountry.countries} | {"XK"})
    # CLDR uses a typographic apostrophe (U+2019), like in Côte d'Ivoire. A
    # plain one is what people type when they search or sort.
    names = {
        code: territories[ALTERNATIVES.get(code, code)].replace("\u2019", "'")
        for code in codes
    }

    # A JSON string is a valid Python string, in the double quotes ruff wants.
    body = "\n".join(
        f"    {json.dumps(code)}: {json.dumps(name, ensure_ascii=False)},"
        for code, name in names.items()
    )
    OUTPUT.write_text(
        f'''"""English names of countries, by ISO 3166-1 alpha-2 code.

Generated by scripts/update_country_names.py from the Unicode CLDR
{CLDR_VERSION}. Do not edit this file by hand, run that script instead.
"""

COUNTRY_NAMES: dict[str, str] = {{
{body}
}}
''',
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
